---

- hosts: all
  become: true
  tasks:

  - name: updates package cache
    apt: update_cache=yes cache_valid_time=600

  - name: upgrade packages
    apt: upgrade=dist
    register: apt_result

  - name: autoremove old packages
    command: apt autoremove -y
    register: apt_result
    changed_when: "'packages will be REMOVED' in apt_result.stout"

*  - name: Purge residual kernel packages
*    shell: apt-get remove -y --purge $(dpkg -l | grep "^rc\s*linux-image-" | awk '{print $2}' | tr '\n' ' ')
*    register: apt_result
*    changed_when: "'packages will be REMOVED' in apt_result.stdout"
